export const MODULE_LIST = "MODULE_LIST";
export const MODULE_LIST_SUCCESS = "MODULE_LIST_SUCCESS";
export const MODULE_LIST_FAIL = "MODULE_LIST_FAIL";

export const EXPERTS = "EXPERTS";
export const EXPERTS_SUCCESS = "EXPERTS_SUCCESS";
export const EXPERTS_FAIL = "EXPERTS_FAIL";

export const MODULE_DETAIL = "MODULE_DETAIL";
export const MODULE_DETAIL_SUCCESS = "MODULE_DETAIL_SUCCESS";
export const MODULE_DETAIL_FAIL = "MODULE_DETAIL_FAIL";
export const CHAPTER_DETAILS = "CHAPTER_DETAILS";